name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes

      - name: Calendar Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          committer_message: "chore: update metrics calendar [skip ci]"